name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    name: Test
    if: ${{ !github.event.pull_request.draft }}
    uses: "./.github/workflows/deploy-template.yml"
    secrets: inherit 
    with:
      environment-name: 'Test'
      webapp-name: 'samling1-api-test'
