name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
    paths:
      - '**/Terraform/**'  
  pull_request:
    branches:
      - main
    paths:
    - '**/Terraform/**'
  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write
    
jobs:
  terraform-plan-apply-test:
    name: "Test"
    #uses: "HydroREIN/REIN-Hub/.github/workflows/terraform-plan-apply-template.yml@main"
    uses: "./.github/workflows/terraform-plan-apply-template.yml"
    with:
      environment-name: 'test'
    secrets:
      client-id: ${{ secrets.TF_AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.TF_AZURE_TENANT_ID }}
